// 70 hand-curated standalone API providers. Each row is intentionally minimal
// — Stagehand's agent primitive handles unfamiliar forms with the generic
// prompt. extra_hint is only set when there's a non-obvious step.
//
// All targets have been verified as: email-only signup, free tier, no phone,
// no credit card required for first key issuance.

import type { Recipe } from "../lib/types.ts";

export const STANDALONE_RECIPES: Recipe[] = [
  // ─── Weather (5) ──────────────────────────────────────────────────────
  {
    name: "openweather",
    display_name: "OpenWeather",
    category: "weather",
    signup_url: "https://home.openweathermap.org/users/sign_up",
    dashboard_url: "https://home.openweathermap.org/api_keys",
    needs_email_verify: true,
    extra_hint: "After confirming email, the default API key is auto-generated and shown in a table on the API keys page.",
    smoke_test: {
      url: "https://api.openweathermap.org/data/2.5/weather?q=London&appid={KEY}",
      expect_body_contains: "London",
    },
  },
  {
    name: "weatherapi",
    display_name: "WeatherAPI.com",
    category: "weather",
    signup_url: "https://www.weatherapi.com/signup.aspx",
    dashboard_url: "https://www.weatherapi.com/my/",
    needs_email_verify: false,
    smoke_test: { url: "https://api.weatherapi.com/v1/current.json?key={KEY}&q=London" },
  },
  {
    name: "tomorrow_io",
    display_name: "Tomorrow.io",
    category: "weather",
    signup_url: "https://app.tomorrow.io/signup",
    dashboard_url: "https://app.tomorrow.io/development/keys",
    needs_email_verify: true,
    smoke_test: {
      url: "https://api.tomorrow.io/v4/weather/realtime?location=london&apikey={KEY}",
    },
  },
  {
    name: "visual_crossing",
    display_name: "Visual Crossing Weather",
    category: "weather",
    signup_url: "https://www.visualcrossing.com/weather-api",
    dashboard_url: "https://www.visualcrossing.com/account",
    needs_email_verify: true,
    smoke_test: {
      url: "https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/london?key={KEY}",
    },
  },
  {
    name: "weatherbit",
    display_name: "Weatherbit",
    category: "weather",
    signup_url: "https://www.weatherbit.io/account/create",
    dashboard_url: "https://www.weatherbit.io/account/dashboard",
    needs_email_verify: true,
    smoke_test: { url: "https://api.weatherbit.io/v2.0/current?city=London&key={KEY}" },
  },

  // ─── Maps / Geo (8) ──────────────────────────────────────────────────
  {
    name: "mapbox",
    display_name: "Mapbox",
    category: "maps",
    signup_url: "https://account.mapbox.com/auth/signup/",
    dashboard_url: "https://account.mapbox.com/access-tokens/",
    needs_email_verify: true,
    extra_hint: "A default public token is created automatically. Use that one.",
    smoke_test: {
      url: "https://api.mapbox.com/geocoding/v5/mapbox.places/london.json?access_token={KEY}",
    },
  },
  {
    name: "geoapify",
    display_name: "Geoapify",
    category: "maps",
    signup_url: "https://myprojects.geoapify.com/register",
    dashboard_url: "https://myprojects.geoapify.com/projects",
    needs_email_verify: true,
    extra_hint: "Create a new project after verifying email. The API key shows on the project page.",
    smoke_test: {
      url: "https://api.geoapify.com/v1/geocode/search?text=london&apiKey={KEY}",
    },
  },
  {
    name: "here_maps",
    display_name: "HERE Maps",
    category: "maps",
    signup_url: "https://platform.here.com/sign-up",
    dashboard_url: "https://platform.here.com/projects",
    needs_email_verify: true,
    extra_hint: "Create a project, then generate an API Key (not OAuth client) in project settings.",
    smoke_test: {
      url: "https://geocode.search.hereapi.com/v1/geocode?q=london&apiKey={KEY}",
    },
  },
  {
    name: "locationiq",
    display_name: "LocationIQ",
    category: "maps",
    signup_url: "https://locationiq.com/register",
    dashboard_url: "https://my.locationiq.com/dashboard",
    needs_email_verify: true,
    smoke_test: {
      url: "https://us1.locationiq.com/v1/search?key={KEY}&q=london&format=json",
    },
  },
  {
    name: "tomtom",
    display_name: "TomTom Maps",
    category: "maps",
    signup_url: "https://developer.tomtom.com/user/register",
    dashboard_url: "https://developer.tomtom.com/user/me/apps",
    needs_email_verify: true,
    smoke_test: {
      url: "https://api.tomtom.com/search/2/geocode/london.json?key={KEY}",
    },
  },
  {
    name: "maptiler",
    display_name: "MapTiler",
    category: "maps",
    signup_url: "https://cloud.maptiler.com/auth/widget?mode=signup",
    dashboard_url: "https://cloud.maptiler.com/account/keys/",
    needs_email_verify: true,
    smoke_test: {
      url: "https://api.maptiler.com/geocoding/london.json?key={KEY}",
    },
  },
  {
    name: "stadia_maps",
    display_name: "Stadia Maps",
    category: "maps",
    signup_url: "https://client.stadiamaps.com/signup/",
    dashboard_url: "https://client.stadiamaps.com/dashboard/",
    needs_email_verify: true,
    extra_hint: "After verifying email, create a 'Property' and an API key under it.",
    smoke_test: {
      url: "https://api.stadiamaps.com/geocoding/v1/search?text=london&api_key={KEY}",
    },
  },
  {
    name: "ipinfo",
    display_name: "IPinfo",
    category: "maps",
    signup_url: "https://ipinfo.io/signup",
    dashboard_url: "https://ipinfo.io/account/token",
    needs_email_verify: true,
    smoke_test: { url: "https://ipinfo.io/8.8.8.8?token={KEY}" },
  },

  // ─── News (5) ─────────────────────────────────────────────────────────
  {
    name: "newsapi_org",
    display_name: "NewsAPI.org",
    category: "news",
    signup_url: "https://newsapi.org/register",
    dashboard_url: "https://newsapi.org/account",
    needs_email_verify: false,
    extra_hint: "The API key is shown directly after submitting the signup form.",
    smoke_test: { url: "https://newsapi.org/v2/top-headlines?country=us&apiKey={KEY}" },
  },
  {
    name: "gnews",
    display_name: "GNews",
    category: "news",
    signup_url: "https://gnews.io/register",
    dashboard_url: "https://gnews.io/dashboard",
    needs_email_verify: true,
    smoke_test: { url: "https://gnews.io/api/v4/top-headlines?lang=en&apikey={KEY}" },
  },
  {
    name: "currents",
    display_name: "Currents API",
    category: "news",
    signup_url: "https://currentsapi.services/en/register",
    dashboard_url: "https://currentsapi.services/en/dashboard",
    needs_email_verify: true,
    smoke_test: { url: "https://api.currentsapi.services/v1/latest-news?apiKey={KEY}" },
  },
  {
    name: "worldnewsapi",
    display_name: "World News API",
    category: "news",
    signup_url: "https://worldnewsapi.com/console/sign-up/",
    dashboard_url: "https://worldnewsapi.com/console/",
    needs_email_verify: true,
    smoke_test: { url: "https://api.worldnewsapi.com/search-news?text=ai&api-key={KEY}" },
  },
  {
    name: "thenewsapi",
    display_name: "TheNewsAPI",
    category: "news",
    signup_url: "https://www.thenewsapi.com/register",
    dashboard_url: "https://www.thenewsapi.com/account/dashboard",
    needs_email_verify: true,
    smoke_test: { url: "https://api.thenewsapi.com/v1/news/top?api_token={KEY}&locale=us" },
  },

  // ─── Finance / Stocks (7) ─────────────────────────────────────────────
  {
    name: "alpha_vantage",
    display_name: "Alpha Vantage",
    category: "finance",
    signup_url: "https://www.alphavantage.co/support/#api-key",
    dashboard_url: "https://www.alphavantage.co/support/#api-key",
    needs_email_verify: false,
    extra_hint: "The key is generated instantly on the same page after filling the small form. No email confirmation.",
    smoke_test: {
      url: "https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=IBM&apikey={KEY}",
    },
  },
  {
    name: "finnhub_signup",
    display_name: "Finnhub (additional key)",
    category: "finance",
    signup_url: "https://finnhub.io/register",
    dashboard_url: "https://finnhub.io/dashboard",
    needs_email_verify: true,
    smoke_test: { url: "https://finnhub.io/api/v1/quote?symbol=AAPL&token={KEY}" },
  },
  {
    name: "twelvedata",
    display_name: "Twelve Data",
    category: "finance",
    signup_url: "https://twelvedata.com/register",
    dashboard_url: "https://twelvedata.com/account/api-keys",
    needs_email_verify: true,
    smoke_test: { url: "https://api.twelvedata.com/quote?symbol=AAPL&apikey={KEY}" },
  },
  {
    name: "polygon",
    display_name: "Polygon.io",
    category: "finance",
    signup_url: "https://polygon.io/dashboard/signup",
    dashboard_url: "https://polygon.io/dashboard/api-keys",
    needs_email_verify: true,
    smoke_test: {
      url: "https://api.polygon.io/v2/aggs/ticker/AAPL/prev?apiKey={KEY}",
    },
  },
  {
    name: "fmp",
    display_name: "Financial Modeling Prep",
    category: "finance",
    signup_url: "https://site.financialmodelingprep.com/register",
    dashboard_url: "https://site.financialmodelingprep.com/developer/docs/dashboard",
    needs_email_verify: true,
    smoke_test: {
      url: "https://financialmodelingprep.com/api/v3/quote/AAPL?apikey={KEY}",
    },
  },
  {
    name: "tradermade",
    display_name: "TraderMade",
    category: "finance",
    signup_url: "https://tradermade.com/signup",
    dashboard_url: "https://tradermade.com/dashboard",
    needs_email_verify: true,
    smoke_test: {
      url: "https://marketdata.tradermade.com/api/v1/live?currency=EURUSD&api_key={KEY}",
    },
  },
  {
    name: "fred",
    display_name: "FRED (St. Louis Fed)",
    category: "finance",
    signup_url: "https://fredaccount.stlouisfed.org/apikeys",
    dashboard_url: "https://fredaccount.stlouisfed.org/apikeys",
    needs_email_verify: true,
    extra_hint: "Free, government-run. After creating account, request a key — it's generated instantly.",
    smoke_test: {
      url: "https://api.stlouisfed.org/fred/series?series_id=GDP&api_key={KEY}&file_type=json",
    },
  },

  // ─── Crypto (4) ──────────────────────────────────────────────────────
  {
    name: "coinmarketcap",
    display_name: "CoinMarketCap",
    category: "crypto",
    signup_url: "https://pro.coinmarketcap.com/signup",
    dashboard_url: "https://pro.coinmarketcap.com/account",
    needs_email_verify: true,
    smoke_test: {
      url: "https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?limit=1",
      headers: { "X-CMC_PRO_API_KEY": "{KEY}" },
    },
  },
  {
    name: "cryptocompare",
    display_name: "CryptoCompare",
    category: "crypto",
    signup_url: "https://www.cryptocompare.com/cryptopian/signup",
    dashboard_url: "https://www.cryptocompare.com/cryptopian/api-keys",
    needs_email_verify: true,
    smoke_test: {
      url: "https://min-api.cryptocompare.com/data/price?fsym=BTC&tsyms=USD&api_key={KEY}",
    },
  },
  {
    name: "messari",
    display_name: "Messari",
    category: "crypto",
    signup_url: "https://messari.io/account/signup",
    dashboard_url: "https://messari.io/account/api",
    needs_email_verify: true,
    smoke_test: {
      url: "https://data.messari.io/api/v1/assets/btc/metrics",
      headers: { "x-messari-api-key": "{KEY}" },
    },
  },
  {
    name: "coinpaprika",
    display_name: "Coinpaprika Pro",
    category: "crypto",
    signup_url: "https://coinpaprika.com/api/signup/",
    dashboard_url: "https://coinpaprika.com/api/panel/",
    needs_email_verify: true,
    smoke_test: {
      url: "https://api-pro.coinpaprika.com/v1/tickers/btc-bitcoin",
      headers: { Authorization: "{KEY}" },
    },
  },

  // ─── Search / Scraping (10) ───────────────────────────────────────────
  {
    name: "brave_search",
    display_name: "Brave Search API",
    category: "search",
    signup_url: "https://api.search.brave.com/register",
    dashboard_url: "https://api.search.brave.com/app/keys",
    needs_email_verify: true,
    extra_hint: "Free 'Data for Search' plan does not require a credit card. Pick that plan.",
    smoke_test: {
      url: "https://api.search.brave.com/res/v1/web/search?q=hello",
      headers: { "X-Subscription-Token": "{KEY}", Accept: "application/json" },
    },
  },
  {
    name: "serper",
    display_name: "Serper.dev",
    category: "search",
    signup_url: "https://serper.dev/signup",
    dashboard_url: "https://serper.dev/api-key",
    needs_email_verify: false,
    extra_hint: "Google OAuth is offered — prefer email signup instead.",
    smoke_test: {
      url: "https://google.serper.dev/search",
      method: "POST",
      headers: { "X-API-KEY": "{KEY}", "Content-Type": "application/json" },
      body: '{"q":"hello"}',
    },
  },
  {
    name: "tavily",
    display_name: "Tavily",
    category: "search",
    signup_url: "https://app.tavily.com/sign-up",
    dashboard_url: "https://app.tavily.com/home",
    needs_email_verify: true,
    smoke_test: {
      url: "https://api.tavily.com/search",
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: '{"api_key":"{KEY}","query":"hello","max_results":1}',
    },
  },
  {
    name: "exa",
    display_name: "Exa.ai",
    category: "search",
    signup_url: "https://dashboard.exa.ai/sign-up",
    dashboard_url: "https://dashboard.exa.ai/api-keys",
    needs_email_verify: true,
    smoke_test: {
      url: "https://api.exa.ai/search",
      method: "POST",
      headers: { "x-api-key": "{KEY}", "Content-Type": "application/json" },
      body: '{"query":"hello","numResults":1}',
    },
  },
  {
    name: "youcom",
    display_name: "You.com API",
    category: "search",
    signup_url: "https://api.you.com/register",
    dashboard_url: "https://api.you.com/dashboard",
    needs_email_verify: true,
    smoke_test: {
      url: "https://api.ydc-index.io/search?query=hello",
      headers: { "X-API-Key": "{KEY}" },
    },
  },
  {
    name: "jina",
    display_name: "Jina AI",
    category: "search",
    signup_url: "https://jina.ai/?login=true",
    dashboard_url: "https://jina.ai/api-dashboard",
    needs_email_verify: true,
    extra_hint: "Jina gives you a starter API key worth ~1M tokens on signup. Copy the key from the dashboard's 'API Key' card.",
    smoke_test: {
      url: "https://r.jina.ai/https://example.com",
      headers: { Authorization: "Bearer {KEY}" },
    },
  },
  {
    name: "scrapingbee",
    display_name: "ScrapingBee",
    category: "search",
    signup_url: "https://app.scrapingbee.com/account/register/",
    dashboard_url: "https://app.scrapingbee.com/account/api-keys",
    needs_email_verify: true,
    smoke_test: {
      url: "https://app.scrapingbee.com/api/v1/?api_key={KEY}&url=https%3A%2F%2Fexample.com",
    },
  },
  {
    name: "scraperapi",
    display_name: "ScraperAPI",
    category: "search",
    signup_url: "https://dashboard.scraperapi.com/signup",
    dashboard_url: "https://dashboard.scraperapi.com/dashboard",
    needs_email_verify: true,
    smoke_test: {
      url: "https://api.scraperapi.com?api_key={KEY}&url=https://example.com",
    },
  },
  {
    name: "zenrows",
    display_name: "ZenRows",
    category: "search",
    signup_url: "https://app.zenrows.com/register",
    dashboard_url: "https://app.zenrows.com/builder",
    needs_email_verify: true,
    smoke_test: {
      url: "https://api.zenrows.com/v1/?apikey={KEY}&url=https%3A%2F%2Fexample.com",
    },
  },
  {
    name: "firecrawl",
    display_name: "Firecrawl",
    category: "search",
    signup_url: "https://www.firecrawl.dev/signin/signup",
    dashboard_url: "https://www.firecrawl.dev/app/api-keys",
    needs_email_verify: true,
    smoke_test: {
      url: "https://api.firecrawl.dev/v1/scrape",
      method: "POST",
      headers: { Authorization: "Bearer {KEY}", "Content-Type": "application/json" },
      body: '{"url":"https://example.com"}',
    },
  },

  // ─── Images / Media (7) ───────────────────────────────────────────────
  {
    name: "unsplash_signup",
    display_name: "Unsplash (additional)",
    category: "media",
    signup_url: "https://unsplash.com/join",
    dashboard_url: "https://unsplash.com/oauth/applications",
    needs_email_verify: true,
    extra_hint: "After joining, create a new application; the Access Key is shown in the application detail page.",
    smoke_test: { url: "https://api.unsplash.com/photos/random?client_id={KEY}" },
  },
  {
    name: "pexels",
    display_name: "Pexels",
    category: "media",
    signup_url: "https://www.pexels.com/join/",
    dashboard_url: "https://www.pexels.com/api/new/",
    needs_email_verify: true,
    smoke_test: {
      url: "https://api.pexels.com/v1/search?query=nature",
      headers: { Authorization: "{KEY}" },
    },
  },
  {
    name: "pixabay",
    display_name: "Pixabay",
    category: "media",
    signup_url: "https://pixabay.com/accounts/register/",
    dashboard_url: "https://pixabay.com/api/docs/",
    needs_email_verify: true,
    extra_hint: "The personal API key is shown to logged-in users on the API docs page.",
    smoke_test: { url: "https://pixabay.com/api/?key={KEY}&q=test" },
  },
  {
    name: "cloudinary",
    display_name: "Cloudinary",
    category: "media",
    signup_url: "https://cloudinary.com/users/register_free",
    dashboard_url: "https://console.cloudinary.com/settings/api-keys",
    needs_email_verify: true,
    extra_hint: "After signup, the API environment variable is shown on the dashboard. Capture the full CLOUDINARY_URL value.",
    smoke_test: { url: "https://api.cloudinary.com/v1_1/demo/resources/image" },
  },
  {
    name: "imagekit",
    display_name: "ImageKit",
    category: "media",
    signup_url: "https://imagekit.io/registration",
    dashboard_url: "https://imagekit.io/dashboard/developer/api-keys",
    needs_email_verify: true,
    smoke_test: { url: "https://api.imagekit.io/v1/files" },
  },
  {
    name: "uploadcare",
    display_name: "Uploadcare",
    category: "media",
    signup_url: "https://app.uploadcare.com/accounts/signup/",
    dashboard_url: "https://app.uploadcare.com/projects/-/api-keys/",
    needs_email_verify: true,
    smoke_test: {
      url: "https://api.uploadcare.com/files/",
      headers: { Authorization: "Uploadcare.Simple {KEY}", Accept: "application/vnd.uploadcare-v0.7+json" },
    },
  },
  {
    name: "bunny_net",
    display_name: "Bunny.net",
    category: "media",
    signup_url: "https://dash.bunny.net/register",
    dashboard_url: "https://dash.bunny.net/account/api",
    needs_email_verify: true,
    extra_hint: "Bunny requires a credit card to activate. If asked for one, abort with SIGNUP_FAILED.",
    smoke_test: {
      url: "https://api.bunny.net/pullzone",
      headers: { AccessKey: "{KEY}" },
    },
  },

  // ─── Audio / Speech (5) ───────────────────────────────────────────────
  {
    name: "elevenlabs",
    display_name: "ElevenLabs",
    category: "audio",
    signup_url: "https://elevenlabs.io/app/sign-up",
    dashboard_url: "https://elevenlabs.io/app/settings/api-keys",
    needs_email_verify: true,
    smoke_test: {
      url: "https://api.elevenlabs.io/v1/voices",
      headers: { "xi-api-key": "{KEY}" },
    },
  },
  {
    name: "assemblyai",
    display_name: "AssemblyAI",
    category: "audio",
    signup_url: "https://www.assemblyai.com/app/signup",
    dashboard_url: "https://www.assemblyai.com/app/account",
    needs_email_verify: true,
    smoke_test: {
      url: "https://api.assemblyai.com/v2/transcript",
      method: "GET",
      headers: { Authorization: "{KEY}" },
    },
  },
  {
    name: "deepgram",
    display_name: "Deepgram",
    category: "audio",
    signup_url: "https://console.deepgram.com/signup",
    dashboard_url: "https://console.deepgram.com/project/_/keys",
    needs_email_verify: true,
    extra_hint: "After verifying email, create a new API key with 'Member' role.",
    smoke_test: {
      url: "https://api.deepgram.com/v1/projects",
      headers: { Authorization: "Token {KEY}" },
    },
  },
  {
    name: "playht",
    display_name: "PlayHT",
    category: "audio",
    signup_url: "https://play.ht/signup/",
    dashboard_url: "https://play.ht/studio/api-access",
    needs_email_verify: true,
    smoke_test: {
      url: "https://api.play.ht/api/v2/voices",
      headers: { Authorization: "Bearer {KEY}", "X-USER-ID": "PLACEHOLDER" },
    },
  },
  {
    name: "speechmatics",
    display_name: "Speechmatics",
    category: "audio",
    signup_url: "https://portal.speechmatics.com/signup/",
    dashboard_url: "https://portal.speechmatics.com/manage-access/",
    needs_email_verify: true,
    smoke_test: {
      url: "https://asr.api.speechmatics.com/v2/jobs/",
      headers: { Authorization: "Bearer {KEY}" },
    },
  },

  // ─── Vector / DB (6) ──────────────────────────────────────────────────
  {
    name: "pinecone",
    display_name: "Pinecone",
    category: "vector_db",
    signup_url: "https://app.pinecone.io/?sessionType=signup",
    dashboard_url: "https://app.pinecone.io/organizations/-/projects/-/keys",
    needs_email_verify: true,
    oauth_only: false,
    extra_hint: "Prefer email signup over Google OAuth. After verifying email, create a project — the default key shows on the keys page.",
    smoke_test: {
      url: "https://api.pinecone.io/indexes",
      headers: { "Api-Key": "{KEY}" },
    },
  },
  {
    name: "qdrant_cloud",
    display_name: "Qdrant Cloud",
    category: "vector_db",
    signup_url: "https://cloud.qdrant.io/signup",
    dashboard_url: "https://cloud.qdrant.io/accounts/-/api-keys",
    needs_email_verify: true,
    smoke_test: { url: "https://cloud.qdrant.io/api/account" },
  },
  {
    name: "weaviate_cloud",
    display_name: "Weaviate Cloud",
    category: "vector_db",
    signup_url: "https://console.weaviate.cloud/sign-in",
    dashboard_url: "https://console.weaviate.cloud/dashboard",
    needs_email_verify: true,
    smoke_test: { url: "https://console.weaviate.cloud/api/v1/clusters" },
  },
  {
    name: "upstash_vector",
    display_name: "Upstash Vector",
    category: "vector_db",
    signup_url: "https://console.upstash.com/login",
    dashboard_url: "https://console.upstash.com/vector",
    needs_email_verify: true,
    extra_hint: "GitHub OAuth is offered — prefer email signup.",
    smoke_test: { url: "https://api.upstash.com/v2/vector/index" },
  },
  {
    name: "neon",
    display_name: "Neon (serverless Postgres)",
    category: "vector_db",
    signup_url: "https://console.neon.tech/signup",
    dashboard_url: "https://console.neon.tech/app/settings/api-keys",
    needs_email_verify: true,
    smoke_test: {
      url: "https://console.neon.tech/api/v2/projects",
      headers: { Authorization: "Bearer {KEY}" },
    },
  },
  {
    name: "supabase",
    display_name: "Supabase",
    category: "vector_db",
    signup_url: "https://supabase.com/dashboard/sign-up",
    dashboard_url: "https://supabase.com/dashboard/account/tokens",
    needs_email_verify: true,
    extra_hint: "Create a personal access token (PAT) on the tokens page after signup.",
    smoke_test: {
      url: "https://api.supabase.com/v1/organizations",
      headers: { Authorization: "Bearer {KEY}" },
    },
  },

  // ─── Email infra (4) ──────────────────────────────────────────────────
  {
    name: "resend",
    display_name: "Resend",
    category: "email_infra",
    signup_url: "https://resend.com/signup",
    dashboard_url: "https://resend.com/api-keys",
    needs_email_verify: true,
    smoke_test: {
      url: "https://api.resend.com/api-keys",
      headers: { Authorization: "Bearer {KEY}" },
    },
  },
  {
    name: "loops",
    display_name: "Loops.so",
    category: "email_infra",
    signup_url: "https://app.loops.so/signup",
    dashboard_url: "https://app.loops.so/settings?page=api",
    needs_email_verify: true,
    smoke_test: {
      url: "https://app.loops.so/api/v1/api-key",
      headers: { Authorization: "Bearer {KEY}" },
    },
  },
  {
    name: "plunk",
    display_name: "Plunk",
    category: "email_infra",
    signup_url: "https://app.useplunk.com/auth/signup",
    dashboard_url: "https://app.useplunk.com/projects",
    needs_email_verify: true,
    smoke_test: {
      url: "https://api.useplunk.com/v1/track",
      headers: { Authorization: "Bearer {KEY}" },
    },
  },
  {
    name: "mailtrap",
    display_name: "Mailtrap",
    category: "email_infra",
    signup_url: "https://mailtrap.io/register/signup",
    dashboard_url: "https://mailtrap.io/api-tokens",
    needs_email_verify: true,
    smoke_test: {
      url: "https://mailtrap.io/api/accounts",
      headers: { "Api-Token": "{KEY}" },
    },
  },

  // ─── NLP / LLM standalone (4) ─────────────────────────────────────────
  {
    name: "cohere",
    display_name: "Cohere",
    category: "nlp",
    signup_url: "https://dashboard.cohere.com/welcome/register",
    dashboard_url: "https://dashboard.cohere.com/api-keys",
    needs_email_verify: true,
    smoke_test: {
      url: "https://api.cohere.com/v1/models",
      headers: { Authorization: "Bearer {KEY}" },
    },
  },
  {
    name: "deepinfra",
    display_name: "DeepInfra",
    category: "nlp",
    signup_url: "https://deepinfra.com/login",
    dashboard_url: "https://deepinfra.com/dash/api_keys",
    needs_email_verify: true,
    extra_hint: "GitHub OAuth is offered — prefer email signup.",
    smoke_test: {
      url: "https://api.deepinfra.com/v1/openai/models",
      headers: { Authorization: "Bearer {KEY}" },
    },
  },
  {
    name: "perplexity",
    display_name: "Perplexity API",
    category: "nlp",
    signup_url: "https://www.perplexity.ai/settings/api",
    dashboard_url: "https://www.perplexity.ai/settings/api",
    needs_email_verify: true,
    extra_hint: "Perplexity requires a credit card to issue a key. If the page demands a card before issuing a key, abort.",
    smoke_test: {
      url: "https://api.perplexity.ai/chat/completions",
      method: "POST",
      headers: { Authorization: "Bearer {KEY}", "Content-Type": "application/json" },
      body: '{"model":"llama-3.1-sonar-small-128k-online","messages":[{"role":"user","content":"hi"}]}',
    },
  },
  {
    name: "mistral",
    display_name: "Mistral La Plateforme",
    category: "nlp",
    signup_url: "https://auth.mistral.ai/ui/registration",
    dashboard_url: "https://console.mistral.ai/api-keys/",
    needs_email_verify: true,
    extra_hint: "Mistral often requires phone verification. If a phone field is required, abort.",
    smoke_test: {
      url: "https://api.mistral.ai/v1/models",
      headers: { Authorization: "Bearer {KEY}" },
    },
  },

  // ─── Misc utility (5) ─────────────────────────────────────────────────
  {
    name: "ipgeolocation",
    display_name: "IPGeolocation.io",
    category: "utility",
    signup_url: "https://ipgeolocation.io/signup.html",
    dashboard_url: "https://app.ipgeolocation.io/dashboard",
    needs_email_verify: true,
    smoke_test: { url: "https://api.ipgeolocation.io/ipgeo?apiKey={KEY}&ip=8.8.8.8" },
  },
  {
    name: "exchangerate_api",
    display_name: "ExchangeRate-API",
    category: "utility",
    signup_url: "https://app.exchangerate-api.com/sign-up",
    dashboard_url: "https://app.exchangerate-api.com/dashboard",
    needs_email_verify: true,
    smoke_test: { url: "https://v6.exchangerate-api.com/v6/{KEY}/latest/USD" },
  },
  {
    name: "abstract_api",
    display_name: "Abstract API",
    category: "utility",
    signup_url: "https://app.abstractapi.com/users/signup",
    dashboard_url: "https://app.abstractapi.com/api/ip-geolocation/tester",
    needs_email_verify: true,
    extra_hint: "Each Abstract product has its own key. Capture the IP Geolocation key as the default.",
    smoke_test: { url: "https://ipgeolocation.abstractapi.com/v1/?api_key={KEY}&ip_address=8.8.8.8" },
  },
  {
    name: "hunter_io",
    display_name: "Hunter.io",
    category: "utility",
    signup_url: "https://hunter.io/users/sign_up",
    dashboard_url: "https://hunter.io/api-keys",
    needs_email_verify: true,
    smoke_test: { url: "https://api.hunter.io/v2/account?api_key={KEY}" },
  },
  {
    name: "clearbit",
    display_name: "Clearbit",
    category: "utility",
    signup_url: "https://dashboard.clearbit.com/signup",
    dashboard_url: "https://dashboard.clearbit.com/api",
    needs_email_verify: true,
    extra_hint: "Clearbit has been moved to HubSpot — signup may redirect there. If a free key isn't issued, abort.",
    smoke_test: {
      url: "https://person.clearbit.com/v2/people/find?email=alex@clearbit.com",
      headers: { Authorization: "Bearer {KEY}" },
    },
  },
];
