// APILayer doesn't expose a programmatic catalog of its sub-APIs — one
// dashboard, one key, ~100 APIs. We hard-code the catalog (verified against
// their marketplace) and assign each one a discrete provider entry.

import type { ProviderConfig } from "../lib/types.ts";

// Each entry: { slug used by APILayer routing, friendly name, sample probe path }
const APILAYER_SUB_APIS: Array<{ slug: string; name: string; category: string; sample: string }> = [
  { slug: "currency_data", name: "Currency Data (currencylayer)", category: "finance", sample: "live?source=USD&currencies=EUR" },
  { slug: "exchangerates_data", name: "Exchange Rates Data", category: "finance", sample: "latest?base=USD&symbols=EUR" },
  { slug: "fixer", name: "Fixer FX", category: "finance", sample: "latest?base=EUR&symbols=USD" },
  { slug: "marketstack", name: "marketstack stocks", category: "finance", sample: "eod/latest?symbols=AAPL" },
  { slug: "polygon-financials", name: "Polygon Financials (APILayer)", category: "finance", sample: "reference/tickers?ticker=AAPL" },
  { slug: "yahoofinance_api", name: "Yahoo Finance API", category: "finance", sample: "summary?symbol=AAPL" },
  { slug: "commodities-api", name: "Commodities API", category: "finance", sample: "latest?base=USD&symbols=GOLD" },
  { slug: "geocoding-api", name: "Geocoding API (APILayer)", category: "maps", sample: "geocode/forward?location=london" },
  { slug: "positionstack", name: "positionstack geo", category: "maps", sample: "forward?query=london" },
  { slug: "ip_to_location", name: "IP to Location", category: "maps", sample: "8.8.8.8" },
  { slug: "ipstack", name: "ipstack geo IP", category: "maps", sample: "8.8.8.8" },
  { slug: "ip_intelligence", name: "IP Intelligence", category: "utility", sample: "lookup?ip=8.8.8.8" },
  { slug: "ip-blocklist", name: "IP Blocklist Lookup", category: "utility", sample: "check?ip=8.8.8.8" },
  { slug: "user_agent", name: "User Agent Parser", category: "utility", sample: "parse?user_agent=test" },
  { slug: "weatherstack", name: "weatherstack", category: "weather", sample: "current?query=London" },
  { slug: "weather_api", name: "Weather API (APILayer)", category: "weather", sample: "current?city=London" },
  { slug: "open-weather", name: "Open Weather (APILayer)", category: "weather", sample: "weather?city=London" },
  { slug: "world-weather", name: "World Weather Online", category: "weather", sample: "weather?q=London" },
  { slug: "mediastack", name: "mediastack news", category: "news", sample: "news?keywords=ai" },
  { slug: "news-api", name: "News API (APILayer)", category: "news", sample: "everything?q=ai" },
  { slug: "newsdata", name: "newsdata.io", category: "news", sample: "news?language=en" },
  { slug: "scrapestack", name: "scrapestack scraper", category: "search", sample: "scrape?url=https://example.com" },
  { slug: "screenshot-api", name: "Screenshot API", category: "search", sample: "capture?url=https://example.com" },
  { slug: "screenshotlayer", name: "screenshotlayer", category: "search", sample: "?url=https://example.com" },
  { slug: "spider-api", name: "Spider Web Scraping", category: "search", sample: "crawl?url=https://example.com" },
  { slug: "rapid_translate", name: "Rapid Translate", category: "nlp", sample: "translate?text=hi&target=es" },
  { slug: "language_detection", name: "Language Detection", category: "nlp", sample: "detect?q=hello" },
  { slug: "text_to_speech", name: "Text to Speech (APILayer)", category: "audio", sample: "synthesize?text=hi" },
  { slug: "transcription_api", name: "Transcription API", category: "audio", sample: "?file_url=https://example.com/a.mp3" },
  { slug: "sentiment-analysis", name: "Sentiment Analysis", category: "nlp", sample: "analyze?text=I love it" },
  { slug: "entity-extraction", name: "Entity Extraction", category: "nlp", sample: "extract?text=Apple is in Cupertino" },
  { slug: "ocr", name: "OCR (APILayer)", category: "media", sample: "image?image=https://example.com/a.png" },
  { slug: "image-recognition", name: "Image Recognition", category: "media", sample: "recognize?url=https://example.com/a.jpg" },
  { slug: "image-resize", name: "Image Resize", category: "media", sample: "resize?url=https://example.com/a.jpg" },
  { slug: "image-conversion", name: "Image Conversion", category: "media", sample: "convert?url=https://example.com/a.png&format=jpg" },
  { slug: "image-classification", name: "Image Classification", category: "media", sample: "classify?url=https://example.com/a.jpg" },
  { slug: "background-removal", name: "Background Removal", category: "media", sample: "remove?url=https://example.com/a.png" },
  { slug: "color_palette", name: "Color Palette", category: "media", sample: "palette?url=https://example.com/a.jpg" },
  { slug: "qr-code-generator", name: "QR Code Generator", category: "utility", sample: "create?text=hi" },
  { slug: "barcode-generator", name: "Barcode Generator", category: "utility", sample: "generate?text=12345" },
  { slug: "url-shortener", name: "URL Shortener", category: "utility", sample: "shorten?url=https://example.com" },
  { slug: "email-verification", name: "Email Verification", category: "utility", sample: "check?email=test@example.com" },
  { slug: "phone-validator", name: "Phone Validator", category: "utility", sample: "validate?number=14155552671" },
  { slug: "numverify", name: "numverify phone validate", category: "utility", sample: "validate?number=14155552671" },
  { slug: "iban-validator", name: "IBAN Validator", category: "utility", sample: "validate?iban=DE89370400440532013000" },
  { slug: "vatlayer", name: "vatlayer VAT validate", category: "utility", sample: "validate?vat_number=LU26375245" },
  { slug: "vat-validation", name: "VAT Validation", category: "utility", sample: "validate?number=LU26375245" },
  { slug: "company-data", name: "Company Data", category: "utility", sample: "lookup?domain=apple.com" },
  { slug: "domain_lookup", name: "Domain Lookup", category: "utility", sample: "?domain=apple.com" },
  { slug: "dns-lookup", name: "DNS Lookup", category: "utility", sample: "?domain=apple.com" },
  { slug: "whois-lookup", name: "WHOIS Lookup", category: "utility", sample: "?domain=apple.com" },
  { slug: "url-meta", name: "URL Meta Scraper", category: "utility", sample: "?url=https://example.com" },
  { slug: "html-extractor", name: "HTML Extractor", category: "utility", sample: "?url=https://example.com" },
  { slug: "pdf-conversion", name: "PDF Conversion", category: "utility", sample: "?url=https://example.com" },
  { slug: "youtube-mp3", name: "YouTube to MP3", category: "media", sample: "?url=https://youtube.com/x" },
  { slug: "world_holidays", name: "World Holidays", category: "utility", sample: "list?country=US&year=2025" },
  { slug: "movie_database", name: "Movie Database", category: "utility", sample: "search?query=inception" },
  { slug: "nutrition", name: "Nutrition API", category: "utility", sample: "search?query=apple" },
  { slug: "food-database", name: "Food Database", category: "utility", sample: "search?q=banana" },
  { slug: "recipes", name: "Recipes API", category: "utility", sample: "search?q=pasta" },
  { slug: "covid19", name: "Covid19 Statistics", category: "utility", sample: "summary" },
  { slug: "currency-conversion", name: "Currency Conversion", category: "finance", sample: "convert?from=USD&to=EUR&amount=10" },
  { slug: "currency-historical", name: "Currency Historical", category: "finance", sample: "historical?date=2024-01-01&base=USD" },
  { slug: "fx-rates", name: "FX Rates", category: "finance", sample: "rates?base=USD" },
  { slug: "crypto_prices", name: "Crypto Prices", category: "crypto", sample: "prices?symbols=BTC,ETH" },
  { slug: "crypto-data", name: "Crypto Data", category: "crypto", sample: "tickers" },
  { slug: "bin-list", name: "BIN Lookup", category: "utility", sample: "401288" },
  { slug: "address-validator", name: "Address Validator", category: "utility", sample: "validate?address=1+main+st" },
  { slug: "lookup", name: "Generic Lookup", category: "utility", sample: "?q=test" },
  { slug: "company-lookup", name: "Company Lookup", category: "utility", sample: "?domain=apple.com" },
  { slug: "stock-prices", name: "Stock Prices", category: "finance", sample: "quote?symbol=AAPL" },
  { slug: "icon-finder", name: "Icon Finder", category: "media", sample: "search?q=cat" },
  { slug: "shutterstock", name: "Shutterstock", category: "media", sample: "images/search?query=nature" },
  { slug: "logo-api", name: "Logo API", category: "media", sample: "?domain=apple.com" },
  { slug: "favicon", name: "Favicon Grabber", category: "media", sample: "?domain=apple.com" },
  { slug: "page-speed", name: "Page Speed", category: "utility", sample: "?url=https://example.com" },
  { slug: "web-of-trust", name: "Web of Trust", category: "utility", sample: "?domain=apple.com" },
  { slug: "ssl-checker", name: "SSL Checker", category: "utility", sample: "?host=example.com" },
  { slug: "port-scanner", name: "Port Scanner", category: "utility", sample: "?host=example.com" },
  { slug: "header-check", name: "HTTP Header Check", category: "utility", sample: "?url=https://example.com" },
  { slug: "html-validator", name: "HTML Validator", category: "utility", sample: "?url=https://example.com" },
  { slug: "broken-links", name: "Broken Links", category: "utility", sample: "?url=https://example.com" },
  { slug: "robots-txt", name: "robots.txt Lookup", category: "utility", sample: "?url=https://example.com" },
  { slug: "sitemap-extractor", name: "Sitemap Extractor", category: "utility", sample: "?url=https://example.com" },
  { slug: "tech-stack", name: "Tech Stack Detector", category: "utility", sample: "?url=https://example.com" },
  { slug: "open-graph", name: "Open Graph", category: "utility", sample: "?url=https://example.com" },
  { slug: "rss", name: "RSS Parser", category: "utility", sample: "?url=https://example.com/rss" },
  { slug: "feed-parser", name: "Feed Parser", category: "utility", sample: "?url=https://example.com/feed" },
  { slug: "html-to-pdf", name: "HTML to PDF", category: "utility", sample: "?html=hi" },
  { slug: "pdf-to-text", name: "PDF to Text", category: "utility", sample: "?url=https://example.com/a.pdf" },
  { slug: "youtube-transcript", name: "YouTube Transcript", category: "utility", sample: "?video_id=x" },
  { slug: "youtube-info", name: "YouTube Info", category: "utility", sample: "?video_id=x" },
  { slug: "vimeo-info", name: "Vimeo Info", category: "utility", sample: "?video_id=x" },
  { slug: "tiktok-info", name: "TikTok Info", category: "utility", sample: "?url=https://tiktok.com/x" },
  { slug: "instagram-info", name: "Instagram Info", category: "utility", sample: "?url=https://instagram.com/x" },
  { slug: "social-meta", name: "Social Meta", category: "utility", sample: "?url=https://example.com" },
  { slug: "twitter-meta", name: "Twitter Meta", category: "utility", sample: "?handle=jack" },
  { slug: "spotify-tracks", name: "Spotify Track Search", category: "utility", sample: "?q=imagine" },
  { slug: "geographic-data", name: "Geographic Data", category: "maps", sample: "country?code=US" },
  { slug: "city-info", name: "City Info", category: "maps", sample: "?city=London" },
  { slug: "country-data", name: "Country Data", category: "maps", sample: "?code=US" },
  { slug: "timezone-api", name: "Timezone API", category: "maps", sample: "?location=London" },
];

export async function enumerateAPILayer(apiKey: string): Promise<ProviderConfig[]> {
  if (!apiKey) throw new Error("APILAYER_API_KEY not set");
  const now = new Date().toISOString();

  return APILAYER_SUB_APIS.map((api) => ({
    id: `apilayer_${api.slug.replace(/[-]/g, "_")}`,
    name: api.name,
    category: api.category as ProviderConfig["category"],
    description: `${api.name} via APILayer (shared key, ${api.slug}).`,
    api_key: apiKey,
    base_url: `https://api.apilayer.com/${api.slug}`,
    auth_header: "apikey: {KEY}",
    source: "apilayer",
    sample_endpoint: {
      url: `https://api.apilayer.com/${api.slug}/${api.sample}`,
      headers: { apikey: "{KEY}" },
    },
    generated_at: now,
  }));
}
